stimulus_duration: 1500 # duration in milliseconds
cross_duration: 3000 # duration in milliseconds
black_screen_duration: 3000 # duration in milliseconds
run_start_pause: 3000 # duration in milliseconds @delfina add pause after button press

num_trials: 6  # number of trials per stimuli 4 normally, for long 6 -> will show num_trials * num_stimuli (=3) per block
num_repetitions: 3 # number of repetitions for the reaction test
num_max_runs: 2 # first 6 then break then 2 more with 6 num_trials

stimuli: ['left'  , 'right', 'circle'] # stimuli to be presented in the experiment
images:
  left: "left_arrow.jpg"
  right: "right_arrow.jpg"
  circle: "circle.jpg"
  cross: "cross.jpg"

Markers:
  start: "START_ARROW_SURVEY_PARADIGM"
  end: "END_ARROW_SURVEY_PARADIGM"
  start_trial: "START_TRIAL"
  end_trial: "END_TRIAL"
  reactiontest_start: "START_REACTION"
  reactiontest_end: "END_REACTION"
  start_stimulus: "START_STIMULUS"
  end_stimulus: "END_STIMULUS"
  survey_start: "START_SURVEY"
  survey_end: "END_SURVEY"
  left: "ARROW LEFT"
  right: "ARROW RIGHT"
  circle: "CIRCLE"
  cross: " ONSET"
  offset: "BLACKSCREEN"


video_path: 
  eng: "instructions.mp4"
  de: "instructions_deutsch.mp4"

questions_eng:
  - question: "Any special to comment from instructor?"
    image:
    type: "entry"
    default: "no"

questions_de:
  - question: "Gibt es etwas Besonderes, das der Instruktor kommentieren"
    image:
    type: "entry"
    default: "nein"


break_questions_eng:
  - question: "How pleasant or unpleasant did the task feel? (1-5)"
    image: "pleasantnessv2.jpg"
    type: "options"
    type: "range-text"
    set_answers: ["very unpleasant", "unpleasant", "neutral", "pleasant", "very pleasant"]
    short: "PL"
    min: 1
    max: 5

  - question: "How calm or aroused (activated) did you feel during the task? (1-5)"
    image: "activatednessv2.jpg"
    type: "options"
    type: "range-text"
    set_answers: ["very calm", "calm", "neutral", "aroused", "very aroused"]
    short: "AR"
    min: 1
    max: 5

  - question: "How much control did you feel over the task (1-5)"
    image: "in_controlv2.jpg"
    type: "options"
    type: "range-text"
    short: "CO"
    min: 1
    max: 5
    set_answers: ["no control at all", "a little control", "some control", "quite a lot of control", "full control"]

  - question: "How fatigued or energized did you feel during the task? (1-7)."
    set_answers: ["fully alert, wide awake", "very lively, responsive, but not at peak", "okay, somewhat fresh", "a little tired, less than fresh", "moderately tired, let down","extremely tired, very difficult to concentrate" ,"completely exhausted, unable to function effectively "]
    image: "fatiguescore.jpg"
    type: "range-text"
    short: "FA"
    min: 1
    max: 7
  
break_questions_de:
  - question: "Wie angenehm oder unangenehm war die Aufgabe? (1-5)"
    image: "pleasantnessv2.jpg"
    type: "options"
    type: "range-text"
    set_answers: ["sehr unangenehm", "unangenehm", "neutral", "angenehm", "sehr angenehm"]
    short: "PL"
    min: 1
    max: 5

  - question: "Wie ruhig oder aktiviert (aufgeregt) fuehlst du dich waehrend der Aufgabe? (1-5)"
    image: "activatednessv2.jpg"
    type: "options"
    type: "range-text"
    short: "AR"
    min: 1
    max: 5
    set_answers: ["sehr ruhig", "ruhig", "neutral", "aktiviert (aufgeregt)", "sehr aktiviert (aufgeregt)"]

  - question: "Wie viel Kontrolle hattest du ueber die Aufgabe? (1-5)"
    image: "in_controlv2.jpg"
    type: "options"
    type: "range-text"
    short: "CO"
    min: 1
    max: 5
    set_answers: ["keine Kontrolle", "wenig Kontrolle", "einige Kontrolle", "viel Kontrolle", "vollständige Kontrolle"]

  - question: "Wie muede oder energiegeladen fuehlst du dich? (1 bis 7)"
    set_answers: ["hellwach, sehr aufmerksam", "sehr wach, aber nicht am Leistungshoehepunkt", "okay, einigermaßen frisch", "etwas muede, nicht ganz frisch", "maedig muede, leicht erschoepft", "sehr muede, Konzentration schwierig", "voellig erschoepft, nicht mehr funktionsfaehig"]
    image: "fatiguescore.jpg"
    type: "range-text"
    short: "FA"
    min: 1
    max: 7