# Signal processing parameters
window_size: 250
step_size: 32
fs: 160.0

frequencies:
  - 8.0
  - 30.0
order: 4

# EEG Hardware/Channel setup
channels:
  - "Fp1"
  - "Fp2"
  - "T8"
  - "F4"
  - "Fz"
  - "F3"
  - "T7"
  - "C4"
  - "Cz"
  - "C3"
  - "P4"
  - "Pz"
  - "P3"
  - "PO8"
  - "Oz"
  - "PO7"

remove_channels: # Optional - Maybe for the future
  - "Fp1"
  - "Fp2"

# Data and Classification parameters
model: "Riemann" # Options: CSPSVM, SAE

subjects_ids: # Range if given 2 numbers | List if specific ids
  - 1
  - 10

n_folds: 3
split: 0.8 # (Train-Test split)
random_state: 42
test: "sub-P999" # Options: sub-P999
