# Signal processing parameters
window_size: 250
step_size: 32
fs: 250
resample: "None" # Options: None or int

frequencies:
  - 8
  - 30
order: 8

artefact_removal: "asr" # Options: ar (Artefact Rejection), asr (Artefact Subspace Reconstruction)

# EEG Hardware/Channel setup: only valid for Physionet and P999
channels:
  - "Fp1"
  - "Fp2"
  - "F3"
  - "Fz"
  - "F4"
  - "T7"
  - "C3"
  - "Cz"
  - "C4"
  - "T8"
  - "P3"
  - "Pz"
  - "P4"
  - "PO7"
  - "PO8"
  - "Oz"

remove_channels:
  - "Fp1"
  - "Fp2"
  - "T7"
  - "T8"
  - "Oz"

subjects_ids: # Range if given 2 numbers | List if specific ids
  - 1
  - 15

n_folds: 3
random_state: 42
finetune: "sub-P554" # Options: sub-P999, sub-P554
test: "sub-P554" # Options: sub-P999, sub-P554
target: "sub" # Folder name with all target subject data

# Online
online: "dino" # Options: dino (Needs an active eeg stream), prerecorded (for testing)
replay_subject_id: "Dino-6" # Options: Phy-### (for Physionet data), Dino-## (Plays one dino game from Fina)
ip: "127.0.0.1" # IP address for UDP communication to the dino game
port: 5005 # Port for the UDP communication to the dino game
classification_threshold: 0.6 # Value between 0 and 1 to determine the confidence threshold for classification
classification_buffer: 10 # Number of classifications to be buffered for majority voting
