questions:
- question: "How difficult was the task? (1-5)"
  image: "difficultyv2.jpg"
  type: "range"
break_questions:
  - question: "How pleasant or unpleasant did the task feel? (1-5)"
    image: "pleasantnessv2.jpg"
    type: "range"
    min: 1
    max: 5

  - question: "How calm or aroused (activated) did you feel during the task? (1-5)"
    image: "activatednessv2.jpg"
    type: "range"
    min: 1
    max: 5
  - question: "How much control did you feel over the task (1-5)"
    image: "in_controlv2.jpg"
    type: "range"
    min: 1
    max: 5
  - question: "How fatigued or energized did you feel during the task?\n (1: fully alert, wide awake -7: completely exhausted, unable to function effectively)"
    image: "fatiguescore.jpg"
    type: "range"
    min: 1
    max: 7
  - question: "How much do you focus on the game (vs on the mental command)?"
    image: "in_controlv2.jpg"
    type: "range"
    min: 1
    max: 5

  - question: "Do you trust in the system?\n 1 (not at all) - 5 (absolutley))"
    image: "pleasantnessv3.jpg"
    type: "range"
    min: 1
    max: 5
  - question: "To what extent did using the BCI feel natural to you?\n 1 (not natural at all) - 5 (completley natural) )"
    image: "in_controlv2.jpg"
    type: "range"
    min: 1
    max: 5 
  - question: "How do you rate the system in predicting your motor intention?\n 1 (no errors, working perfect) 5 (not functioning)"
    image: "pleasantness.jpg"
    type: "range"
    min: 1
    max: 5

break_questions_de:
  - question: "Wie angenehm oder unangenehm war die Aufgabe? (1-5)"
    image: "pleasantnessv2.jpg"
    type: "options"
    type: "range-text"
    set_answers: ["sehr unangenehm", "unangenehm", "neutral", "angenehm", "sehr angenehm"]
    short: "PL"
    min: 1
    max: 5

  - question: "Wie ruhig oder aktiviert (aufgeregt) fuehlst du dich waehrend der Aufgabe? (1-5)"
    image: "activatednessv2.jpg"
    type: "options"
    type: "range-text"
    short: "AR"
    min: 1
    max: 5
    set_answers: ["sehr ruhig", "ruhig", "neutral", "aktiviert (aufgeregt)", "sehr aktiviert (aufgeregt)"]

  - question: "Wie viel Kontrolle hattest du ueber die Aufgabe? (1-5)"
    image: "in_controlv2.jpg"
    type: "options"
    type: "range-text"
    short: "CO"
    min: 1
    max: 5
    set_answers: ["keine Kontrolle", "wenig Kontrolle", "einige Kontrolle", "viel Kontrolle", "vollständige Kontrolle"]

  - question: "Wie muede oder energiegeladen fuehlst du dich? (1 bis 7)"
    set_answers: ["hellwach, sehr aufmerksam", "sehr wach, aber nicht am Leistungshoehepunkt", "okay, einigermaßen frisch", "etwas muede, nicht ganz frisch", "maedig muede, leicht erschoepft", "sehr muede, Konzentration schwierig", "voellig erschoepft, nicht mehr funktionsfaehig"]
    image: "fatiguescore.jpg"
    type: "range-text"
    short: "FA"
    min: 1
    max: 7

  - question: "Wie sehr konzentrierst du dich auf das Spiel (vs auf das mentale)?"
    image: "in_controlv2.jpg"
    type: "range"
    min: 1
    max: 5

  - question: "Vertraust du dem System?\n 1 (gar nicht) - 5 (absolut))"
    image: "pleasantnessv2.jpg"
    type: "range"
    min: 1
    max: 5
  - question: "Wie intuitiv fuehlt sich das Steuern des BCIs an?\n 1 (Gar nicht natuerlich) - 5 (absolut natuerlich) )"
    image: "in_controlv2.jpg"
    type: "range"
    min: 1
    max: 5 
  - question: "Wie bewertest du das System im Erkennen deiner Motorischen Intention?\n 1 (Keine Fehler, einwandfrei) 5 (Funktioniert ueberhaupt nicht)"
    image: "pleasantness.jpg"
    type: "range"
    min: 1
    max: 5
Countdown: 300 # seconds of game play 
success_rate: 0.7 # 0,5more like 30 percent. 0.8 is quite real, 0.1&0.2: 0.2 , 0.3&0.4: 0.33,0.35:0.4,  0.5:46.7 0.6:0.6 ,0.65:0.73, 0.7&0.8 :0.86, 0.9:100, [ 0.2 ,0.33, 0.4, 0.47 0.6 ,0.73, 0.86, 1.00]
# 0.6 was the first round  

# we were doing 
game_speed: 15 # speed of the game, 10 is normal, 20 is

quicktime_duration: 3 # duration in seconds

num_reaction_times: 2

day_time: True  # True for day mode, False for night mode
# number of tasks in the game
num_tasks: 4  # Adjust as needed, e.g., 3 for three tasks per marker

prob_threshold: 0.5  # Threshold for no marker prediction

evidence_window: 0.6  # Time window for evidence accumulation in seconds
ignore_first_s: 0.3  # Ignore first second of the game for evidence accumulation
min_votes: 6
refractory_s: 0.35  # Refractory period in seconds

debug_hud: False  # Enable or disable debug HUD
stale_pred_s: 1.0  # Time in seconds to consider a prediction stale
fallback_max_bumps: 3  # Maximum number of fallback humps

sleep_time: 0.3  # Sleep time in seconds for debounce